### ISSUE TITLE
`main` 브랜치에 PR 머지 후 작업.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/parking-android#133]
1. `main` 브랜치로 머지하는 PR만 대상으로 한다.
2. 브랜치 검사는 `ci-working-branch`에서 실행한다.
3. 머지된 후에 작업.

## TODO

1. [x] `main` 브랜치에 빌드 태그를 작성한다.
2. [x] 해당 태그에 [릴리즈](https://docs.github.com/repositories/releasing-projects-on-github/managing-releases-in-a-repository)를 생성한다.
3. [x] `debug` 빌드한 AAB 파일을 릴리즈에 추가한다.
