### ISSUE TITLE
장소 검색하기.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/parking-android#34]
지도 오버레이 UI에서 장소 검색 진행하기.

## TODO

- [x] 검색어 입력으로 Places API 호출하기.
- [x] 검색 `Job`을 한번에 하나만 실행하기.
- [x] 검색 결과를 하단 결과 UI에 출력하기.
- [ ] ~~검색 결과 페이징.~~ #39 로 분리.

## NOT DO

1. 검색 결과를 지도에 표시하기. 지도 연동은 별도 이슈로 처리.
